# Generated by Django 3.0.8 on 2020-07-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200707_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='recorded_on',
            field=models.DateField(),
        ),
    ]
